# Trivial muddle makefile
all:
	@echo Make all for '$(MUDDLE_LABEL)'
	$(CC) $(MUDDLE_SRC)/{progname}.c -o $(MUDDLE_OBJ)/{progname}

config:
	@echo Make configure for '$(MUDDLE_LABEL)'

install:
	@echo Make install for '$(MUDDLE_LABEL)'
	cp $(MUDDLE_OBJ)/{progname} $(MUDDLE_INSTALL)

clean:
	@echo Make clean for '$(MUDDLE_LABEL)'

distclean:
	@echo Make distclean for '$(MUDDLE_LABEL)'

.PHONY: all config install clean distclean
