EXTRA_CPPFLAGS += $(MUDDLE_INCLUDE_DIRS:%=-I%)
EXTRA_LDFLAGS += $(MUDDLE_LIB_DIRS:%=-L%)

BUILD_DIR ?= $(MUDDLE_OBJ)
OBJDIR ?= $(MUDDLE_OBJ_OBJ)
INSTALL_DIR ?= $(MUDDLE_INSTALL)
INST_INCDIR ?= $(MUDDLE_OBJ)/include

BASE_DIR ?= $(MUDDLE_SRC)

include rules.mk
