# Sample muddle makefile for a package using autoconf

CFLAGS=$(MUDDLE_INCLUDE_DIRS:%=-I%)
LDFLAGS=$(MUDDLE_LIB_DIRS:%=-L%)

all:
	make -C $(MUDDLE_OBJ_OBJ)

install:
	make -C $(MUDDLE_OBJ_OBJ) DESTDIR=$(MUDDLE_INSTALL) install

config:
	-rm -rf $(MUDDLE_OBJ)
	mkdir -p $(MUDDLE_OBJ_OBJ)
	(cd $(MUDDLE_OBJ_OBJ); $(MUDDLE_SRC)/configure --prefix=/usr)

clean:
	make -C $(MUDDLE_OBJ_OBJ) clean

distclean:
	rm -rf $(MUDDLE_OBJ_OBJ)


# End file.

